
package com.opensingular.ws.requirement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RequirementsampleService", targetNamespace = "com.opensingular", wsdlLocation = "http://localhost:8080/singularee/ws/Requirementsample?wsdl")
public class RequirementsampleService
    extends Service
{

    private final static URL REQUIREMENTSAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException REQUIREMENTSAMPLESERVICE_EXCEPTION;
    private final static QName REQUIREMENTSAMPLESERVICE_QNAME = new QName("com.opensingular", "RequirementsampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/singularee/ws/Requirementsample?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REQUIREMENTSAMPLESERVICE_WSDL_LOCATION = url;
        REQUIREMENTSAMPLESERVICE_EXCEPTION = e;
    }

    public RequirementsampleService() {
        super(__getWsdlLocation(), REQUIREMENTSAMPLESERVICE_QNAME);
    }

    public RequirementsampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REQUIREMENTSAMPLESERVICE_QNAME, features);
    }

    public RequirementsampleService(URL wsdlLocation) {
        super(wsdlLocation, REQUIREMENTSAMPLESERVICE_QNAME);
    }

    public RequirementsampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REQUIREMENTSAMPLESERVICE_QNAME, features);
    }

    public RequirementsampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequirementsampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RequirementsamplePortType
     */
    @WebEndpoint(name = "RequirementsampleServiceSoap")
    public RequirementsamplePortType getRequirementsampleServiceSoap() {
        return super.getPort(new QName("com.opensingular", "RequirementsampleServiceSoap"), RequirementsamplePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequirementsamplePortType
     */
    @WebEndpoint(name = "RequirementsampleServiceSoap")
    public RequirementsamplePortType getRequirementsampleServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("com.opensingular", "RequirementsampleServiceSoap"), RequirementsamplePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REQUIREMENTSAMPLESERVICE_EXCEPTION!= null) {
            throw REQUIREMENTSAMPLESERVICE_EXCEPTION;
        }
        return REQUIREMENTSAMPLESERVICE_WSDL_LOCATION;
    }

}
