
package com.opensingular.ws.upload;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UploadEndpointWs", targetNamespace = "opensingular.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UploadEndpointWs {


    /**
     * 
     * @param filename
     * @param data
     * @return
     *     returns com.opensingular.ws.upload.AttachmentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileUpload", targetNamespace = "opensingular.com", className = "com.opensingular.ws.upload.FileUpload")
    @ResponseWrapper(localName = "fileUploadResponse", targetNamespace = "opensingular.com", className = "com.opensingular.ws.upload.FileUploadResponse")
    public AttachmentResponse fileUpload(
        @WebParam(name = "filename", targetNamespace = "")
        String filename,
        @WebParam(name = "data", targetNamespace = "")
        DataHandler data);

}
