
package com.opensingular.ws.upload;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "uploadws", targetNamespace = "opensingular.com", wsdlLocation = "http://localhost:8080/singularee/uploadws?wsdl")
public class Uploadws
    extends Service
{

    private final static URL UPLOADWS_WSDL_LOCATION;
    private final static WebServiceException UPLOADWS_EXCEPTION;
    private final static QName UPLOADWS_QNAME = new QName("opensingular.com", "uploadws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/singularee/uploadws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPLOADWS_WSDL_LOCATION = url;
        UPLOADWS_EXCEPTION = e;
    }

    public Uploadws() {
        super(__getWsdlLocation(), UPLOADWS_QNAME);
    }

    public Uploadws(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADWS_QNAME, features);
    }

    public Uploadws(URL wsdlLocation) {
        super(wsdlLocation, UPLOADWS_QNAME);
    }

    public Uploadws(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADWS_QNAME, features);
    }

    public Uploadws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Uploadws(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UploadEndpointWs
     */
    @WebEndpoint(name = "UploadWsPort")
    public UploadEndpointWs getUploadWsPort() {
        return super.getPort(new QName("opensingular.com", "UploadWsPort"), UploadEndpointWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadEndpointWs
     */
    @WebEndpoint(name = "UploadWsPort")
    public UploadEndpointWs getUploadWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("opensingular.com", "UploadWsPort"), UploadEndpointWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADWS_EXCEPTION!= null) {
            throw UPLOADWS_EXCEPTION;
        }
        return UPLOADWS_WSDL_LOCATION;
    }

}
