CREATE TABLE T_DEMANDA (
  ID             INT AUTO_INCREMENT,
  TITULO         VARCHAR(200) NOT NULL,
  ID_DEMANDANTE  INT,
  ID_ATENDENTE   INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_DEMANDANTE) REFERENCES T_PESSOA,
  FOREIGN KEY (ID_ATENDENTE) REFERENCES T_PESSOA
);

INSERT INTO T_DEMANDA ( TITULO, ID_DEMANDANTE, ID_ATENDENTE ) VALUES ('Treinamento in-loco dia 11/dez', 1, 2);
INSERT INTO T_DEMANDA ( TITULO, ID_DEMANDANTE, ID_ATENDENTE ) VALUES ('Treinamento in-loco dia 21/dez', 1, 4);
