INSERT INTO DBSINGULAR.TB_MODULO VALUES
(
'REQUIREMENTSAMPLE',
'REQUIREMENTSAMPLE',
'https://localhost:8443'
);


insert into dbsingular.tb_parametro (CO_PARAMETRO, CO_MODULO, NO_PARAMETRO, VL_PARAMETRO) values (1 ,'REQUIREMENTSAMPLE','ADMIN_HASH_PASSWORD','0aca995b93addee9348dcef9016c0f9624dfae3a');
insert into dbsingular.tb_parametro (CO_PARAMETRO, CO_MODULO, NO_PARAMETRO, VL_PARAMETRO) values (2, 'REQUIREMENTSAMPLE','ADMIN_USERNAME','singular');
