INSERT INTO TD_TIPO_DOSE VALUES (1, 'g/hectare', 'S');
INSERT INTO TD_TIPO_DOSE VALUES (2, 'g/m3', 'S');

INSERT INTO TD_CULTURA VALUES (1, 'Milho', 'S');
INSERT INTO TD_CULTURA VALUES (2, 'Feijão', 'S');
INSERT INTO TD_CULTURA VALUES (3, 'Arroz', 'S');

INSERT INTO TD_MODALIDADE_EMPREGO VALUES (1, 'Raiz', 'S');
INSERT INTO TD_MODALIDADE_EMPREGO VALUES (2, 'Caule', 'S');
INSERT INTO TD_MODALIDADE_EMPREGO VALUES (3, 'Folha', 'S');

INSERT INTO TD_NORMA VALUES (1, 'Portaria nº 3, de 16 de janeiro de 1992', 'S');
INSERT INTO TD_NORMA VALUES (2, 'RDC n° 44, de 10 de maio de 2000', 'S');
INSERT INTO TD_NORMA VALUES (3, 'RDC n° 216, de 15 de dezembro de 2006', 'S');
INSERT INTO TD_NORMA VALUES (4, 'RDC n° 4, de 18 de janeiro de 2012', 'S');