CREATE TABLE TD_TIPO_DOSE (
  CO_SEQ_TIPO_DOSE  NUMBER,
  NO_TIPO_DOSE      VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1),
  PRIMARY KEY (CO_SEQ_TIPO_DOSE)
);

CREATE TABLE TD_CULTURA (
  CO_SEQ_CULTURA    NUMBER,
  NO_CULTURA        VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1),
  PRIMARY KEY (CO_SEQ_CULTURA)
);

CREATE TABLE TD_MODALIDADE_EMPREGO (
  CO_SEQ_MODALIDADE_EMPREGO NUMBER,
  NO_MODALIDADE_EMPREGO     VARCHAR(200),
  ST_REGISTRO_ATIVO         CHAR(1),
  PRIMARY KEY (CO_SEQ_MODALIDADE_EMPREGO)
);

CREATE TABLE TD_NORMA (
  CO_SEQ_NORMA      NUMBER,
  NO_NORMA          VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1),
  PRIMARY KEY (CO_SEQ_NORMA)
);

CREATE TABLE TB_ESTUDO_RESIDUOS_TOXICOS (
  CO_SEQ_ESTUDO_RESIDUOS      NUMBER,
  CO_CULTURA                  NUMBER,
  CO_MODALIDADE_EMPREGO       NUMBER,
  CO_TIPO_DOSE                NUMBER,
  CO_NORMA                    NUMBER,
  ST_PARTE_COMESTIVEL         CHAR(1),
  ST_ADJUVANTE                CHAR(1),
  QT_DIAS_INTERVALO_SEGURANCA NUMBER,
  NU_APLICACOES               NUMBER,
  DS_OBSERVACAO               VARCHAR(2000),
  ST_REGISTRO_ATIVO           CHAR(1),
  PRIMARY KEY (CO_SEQ_ESTUDO_RESIDUOS),
  FOREIGN KEY (CO_CULTURA) REFERENCES TD_CULTURA,
  FOREIGN KEY (CO_MODALIDADE_EMPREGO) REFERENCES TD_MODALIDADE_EMPREGO,
  FOREIGN KEY (CO_TIPO_DOSE) REFERENCES TD_TIPO_DOSE,
  FOREIGN KEY (CO_NORMA) REFERENCES TD_NORMA
);

CREATE TABLE TB_ENSAIO_ESTUDO_RESIDUOS (
  CO_SEQ_ENSAIO_ESTUDO NUMBER,
  CO_ESTUDO_RESIDUOS   NUMBER,
  DS_CIDADE            VARCHAR(200),
  DS_CODIGO_ENSAIO     VARCHAR(200),
  ST_REGISTRO_ATIVO    CHAR(1),
  PRIMARY KEY (CO_SEQ_ENSAIO_ESTUDO),
  FOREIGN KEY (CO_ESTUDO_RESIDUOS) REFERENCES TB_ESTUDO_RESIDUOS_TOXICOS
);

CREATE TABLE TB_AMOSTRA_ENSAIO (
  CO_SEQ_AMOSTRA_ENSAIO NUMBER,
  CO_ENSAIO_ESTUDO      NUMBER,
  NU_DOSE               NUMBER,
  QT_DAT                NUMBER,
  QT_LOQ                NUMBER,
  QT_RESIDUO_ENCONTRADO NUMBER,
  ST_POSSUI_METABOLITO  CHAR(1),
  ST_REGISTRO_ATIVO     CHAR(1),
  PRIMARY KEY (CO_SEQ_AMOSTRA_ENSAIO),
  FOREIGN KEY (CO_ENSAIO_ESTUDO) REFERENCES TB_ENSAIO_ESTUDO_RESIDUOS
);

CREATE TABLE TB_METABOLITO_AMOSTRA (
  CO_SEQ_METABOLITO_AMOSTRA NUMBER,
  CO_AMOSTRA_ENSAIO         NUMBER,
      QT_LOQ                    NUMBER,
  QT_RESIDUO_ENCONTRADO     NUMBER,
  ST_REGISTRO_ATIVO         CHAR(1),
  PRIMARY KEY (CO_SEQ_METABOLITO_AMOSTRA),
  FOREIGN KEY (CO_AMOSTRA_ENSAIO) REFERENCES TB_AMOSTRA_ENSAIO
);