DROP ALL OBJECTS;

CREATE TABLE TD_TIPO_DOSE (
  CO_SEQ_TIPO_DOSE  INT AUTO_INCREMENT,
  NO_TIPO_DOSE      VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_TIPO_DOSE)
);

CREATE TABLE TD_CULTURA (
  CO_SEQ_CULTURA    INT AUTO_INCREMENT,
  NO_CULTURA        VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_CULTURA)
);

CREATE TABLE TD_MODALIDADE_EMPREGO (
  CO_SEQ_MODALIDADE_EMPREGO INT AUTO_INCREMENT,
  NO_MODALIDADE_EMPREGO     VARCHAR(200),
  ST_REGISTRO_ATIVO         CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_MODALIDADE_EMPREGO)
);

CREATE TABLE TD_NORMA (
  CO_SEQ_NORMA      INT AUTO_INCREMENT,
  NO_NORMA          VARCHAR(200),
  ST_REGISTRO_ATIVO CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_NORMA)
);

CREATE TABLE TB_ESTUDO_RESIDUOS_TOXICOS (
  CO_SEQ_ESTUDO_RESIDUOS      INT AUTO_INCREMENT,
  CO_CULTURA                  INT,
  CO_MODALIDADE_EMPREGO       INT,
  CO_TIPO_DOSE                INT,
  CO_NORMA                    INT,
  ST_PARTE_COMESTIVEL         CHAR(1),
  ST_ADJUVANTE                CHAR(1),
  QT_DIAS_INTERVALO_SEGURANCA INT,
  NU_APLICACOES               INT,
  DS_OBSERVACAO               VARCHAR(2000),
  ST_REGISTRO_ATIVO           CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_ESTUDO_RESIDUOS),
  FOREIGN KEY (CO_CULTURA) REFERENCES TD_CULTURA,
  FOREIGN KEY (CO_MODALIDADE_EMPREGO) REFERENCES TD_MODALIDADE_EMPREGO,
  FOREIGN KEY (CO_TIPO_DOSE) REFERENCES TD_TIPO_DOSE,
  FOREIGN KEY (CO_NORMA) REFERENCES TD_NORMA
);

CREATE TABLE TB_ENSAIO_ESTUDO_RESIDUOS (
  CO_SEQ_ENSAIO_ESTUDO INT AUTO_INCREMENT,
  CO_ESTUDO_RESIDUOS   INT,
  DS_CIDADE            VARCHAR(200),
  DS_CODIGO_ENSAIO     VARCHAR(200),
  ST_REGISTRO_ATIVO    CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_ENSAIO_ESTUDO),
  FOREIGN KEY (CO_ESTUDO_RESIDUOS) REFERENCES TB_ESTUDO_RESIDUOS_TOXICOS
);

CREATE TABLE TB_AMOSTRA_ENSAIO (
  CO_SEQ_AMOSTRA_ENSAIO INT AUTO_INCREMENT,
  CO_ENSAIO_ESTUDO      INT,
  DS_CODIGO_AMOSTRA     VARCHAR(200),
  NU_DOSE               INT,
  QT_DAT                INT,
  QT_LOQ                INT,
  QT_RESIDUO_ENCONTRADO INT,
  ST_POSSUI_METABOLITO  CHAR(1),
  ST_REGISTRO_ATIVO     CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_AMOSTRA_ENSAIO),
  FOREIGN KEY (CO_ENSAIO_ESTUDO) REFERENCES TB_ENSAIO_ESTUDO_RESIDUOS
);

CREATE TABLE TB_METABOLITO_AMOSTRA (
  CO_SEQ_METABOLITO_AMOSTRA INT AUTO_INCREMENT,
  CO_AMOSTRA_ENSAIO         INT,
  QT_LOQ                    INT,
  QT_RESIDUO_ENCONTRADO     INT,
  ST_REGISTRO_ATIVO         CHAR(1) DEFAULT 'S',
  PRIMARY KEY (CO_SEQ_METABOLITO_AMOSTRA),
  FOREIGN KEY (CO_AMOSTRA_ENSAIO) REFERENCES TB_AMOSTRA_ENSAIO
);